# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sMm7Q7EBHyQc0rZFhmnhUiFhNc4rMhHb
"""

# File: app_logreg.py
import streamlit as st
import joblib

# Load model and vectorizer
model = joblib.load("logreg_fake_news.pkl")
vectorizer = joblib.load("tfidf_vectorizer.pkl")

st.title("Fake News Detection with NLP - Logistic Regression")
st.markdown("**Exposing the truth with advanced fake news detection powered by NLP**")

text = st.text_area("Enter news text here:")
if st.button("Predict"):
    vectorized = vectorizer.transform([text])
    prediction = model.predict(vectorized)[0]
    result = "Real News" if prediction == 0 else "Fake News"
    st.success(f"Prediction: {result}")


# File: train_logreg.py
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import joblib

# Load your dataset
df = pd.read_csv("news.csv")  # Assume columns: 'text', 'label'

# Preprocess
vectorizer = TfidfVectorizer(max_features=5000)
X = vectorizer.fit_transform(df['text'])
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Save model and vectorizer
joblib.dump(model, "logreg_fake_news.pkl")
joblib.dump(vectorizer, "tfidf_vectorizer.pkl")


# File: requirements.txt
streamlit
scikit-learn
pandas
joblib


# Sample file: news.csv
# text,label
# "NASA discovers water on moon",0
# "Aliens confirmed by the president",1